version: "3"

services:

  spring:
      container_name: spring-redis
      image: spring:redis
      build:
        context: .
        dockerfile: Dockerfile
      ports:
      - "8080:8080"
      environment:
        REDIS_HOST: redis
      depends_on:
        - redis
        - wavefront


  redis:
      container_name: redis-server
      image: redis:latest
      hostname: redis
      ports:
      - "6379:6379"

  wavefront:
    container_name: wavefront-proxy
    image: wavefronthq/proxy:latest
    environment:
      WAVEFRONT_URL: ""
      WAVEFRONT_TOKEN: ""
      JAVA_HEAP: "512m"
    ports:
      "2878:2878"


