version: "3"

services:

  spring:
    container_name: spring-redis
    image: spring:redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: mysql
      WAVEFRONT_URL: wavefront
    depends_on:
      - mysql
      - redis
  #   - wavefront

  mysql:
    container_name: spring-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school
    ports:
      - 3306:3306

  redis:
    container_name: redis-server
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379

    #wavefront:
    #  container_name: wavefront-proxy
    #  image: wavefronthq/proxy:latest
    #  environment:
    #WAVEFRONT_URL: ""
    #WAVEFRONT_TOKEN: ""
    #    JAVA_HEAP: "512m"
    # ports:
  #   - 2878:2878


