
name: spring-workflow
on:
  push:
    branch: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Install JDK (Install/Compile)
      - uses: actions/checkout@v2
      - name: Installing Java JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Build Project with Gradle
      - name: Building Project
        run: ./gradlew build
      # Upload to DockerHub
      - uses: actions/checkout@v2
      - name: Create Spring Boot Container
        run: |
          docker login --username=manguilar22 --password=${{ secrets.DOCKER_PW }}
          docker build --tag manguilar22/spring:redis --no-cache --pull --file Dockerfile .
          docker push manguilar22/spring:redis
